# -*- coding: utf-8 -*-
"""Bilingual glossary for WYW / 威驭 cable-chain catalogs."""

# (zh, en) pairs. Longer phrases must appear first after sorting in the converter.
PAIRS = [
    # company / cover
    ("江苏威驭智能科技有限公司", "WYW MOTION (Jiangsu) Co., Ltd."),
    ("威驭智能科技(上海)有限公司", "WYW MOTION (Shanghai) Co., Ltd."),
    ("威驭智能愿景 : 致力于成为世界级运动塑料产品专家,为客户提供更好的产品和服务。",
     "WYW's vision is to become a world-class expert in motion plastics, dedicated to delivering better products and services."),
    ("威驭智能愿景 : 致力于成为世界级运动塑料产品专家,为客户提供更好的产品和服务。",
     "WYW's vision is to become a world-class expert in motion plastics, dedicated to delivering better products and services."),
    ("我们是制造型企业, 我们为制造业服务", "We are a manufacturer serving the manufacturing industry"),
    ("驭威驭拖链系统", "WYW Cable-chain System"),
    ("威驭拖链系统", "WYW Cable Chain System"),
    ("部分客户合作伙伴", "Selected partners"),
    ("公司简介", "Company profile"),
    ("型号概览", "Series overview"),
    ("符号信息", "Legend / terminology"),
    ("项目应用", "Project application"),
    ("拖链附件", "Accessories"),
    ("材料特性", "Material properties"),
    ("技术参数", "Technical data"),
    ("注意事项", "Notes"),
    ("订购示例", "Ordering example"),
    ("产品代码", "Product code"),
    ("拖链代码", "Cable chain code"),
    ("标准物料订购示例", "Standard ordering example"),
    ("特殊应用订购示例", "Special application ordering example"),
    ("例的标准物料订购", "Example of standard material ordering"),
    ("Example of standard material ordering", "标准物料订购示例"),
    # contacts
    ("工厂地址", "Factory address"),
    ("公司地址", "Office address"),
    ("联系地址", "Address"),
    ("联系电话", "Tel"),
    ("技术工程师 联系方式 公司 日期", "Engineer / Contact / Company / Date"),
    ("技术工程师", "Application engineer"),
    ("联系方式", "Contact"),
    # series / TOC
    ("便捷全能型 | 可打开", "Universal | easyclip | openable"),
    ("通用全能型 | 高负载", "Universal | heavy-duty"),
    ("轻载封闭型 | 极小弯曲半径", "Enclosed | minimum bending radius"),
    ("静音重载 | 千级无尘", "Quiet | heavy-duty | ISO Class 3"),
    ("静音便捷 | 千级无尘", "Quiet | convenient | ISO Class 2"),
    ("一片式 | 不可打开", "One-piece | non-openable"),
    ("无尘拖链 | 百级无尘", "Cleanroom cable chain | ISO Class 1"),
    ("各系列规格数字为产品内高", "The number in each series is the inner height"),
    ("系列快速选型 I技术参数", "Quick selection / technical data"),
    ("系列快速选型 l技术参数", "Quick selection / technical data"),
    ("去应力元件      电缆夹 | 扎线板 | C 型槽", "Strain relief: clamps | tiewrap plates | C-profile"),
    ("标准型", "Standard"),
    ("非标型", "Non-standard"),
    # applications
    ("架空应用   短行程", "Unsupported application · short travel"),
    ("滑行应用   长行程", "Sliding application · long travel"),
    ("竖直应用   站立 l 悬挂", "Vertical · standing / hanging"),
    ("侧向应用   侧倒 l 旋转", "Side-mounted · straight / rotary"),
    ("架空应用", "Unsupported"),
    ("滑行应用", "Sliding"),
    ("站立应用", "Standing application"),
    ("悬挂应用", "Hanging application"),
    ("侧倒应用", "Side-mounted application"),
    ("旋转应用", "Rotary application"),
    ("管线排布 分隔原则", "Cable layout and separation"),
    ("合理的管线排布", "Correct cable layout"),
    ("不合理的管线排布", "Incorrect cable layout"),
    ("分隔原则", "Separation rules"),
    ("管线间隙", "Clearance"),
    ("划分规则", "Division rules"),
    ("重量分布", "Weight distribution"),
    ("嵌套安装", "Nested installation"),
    ("对开安装", "Opposing installation"),
    ("免费的设计方案和咨询", "Free design support"),
    # installation types
    ("垂直悬挂", "Vertical hanging"),
    ("竖直站立", "Vertical standing"),
    ("侧向架空", "Side-mounted unsupported"),
    ("侧向直行", "Side-mounted straight"),
    ("直线架空", "Unsupported with straight upper run"),
    ("直线架空", "Unsupported with straight"),
    ("安全塌腰", "Unsupported with permitted sag"),
    ("架空负载", "Unsupported Load"),
    ("架空负载", "Unsupported  Load"),
    ("全套固定式接头代码", "Full set fixed mounting bracket code"),
    ("全套固定式接头", "Full set fixed mounting bracket"),
    ("特点与优势", "Features & Benefits"),
    ("安全塌腰", "Unsupported with permitted sag"),
    ("危险架空", "Critical sag"),
    ("全塌腰", "Full sag"),
    ("直线架空 一 预应力", "Straight unsupported — camber"),
    ("直线架空 一 噪音", "Straight unsupported — noise"),
    ("架空  负载图", "Unsupported-load diagram"),
    ("架空定义", "Unsupported definition"),
    ("架空长度", "Unsupported length"),
    ("架空姿态", "Unsupported posture"),
    ("最大架空长度", "Max unsupported length"),
    ("最大架空负载", "Max unsupported load"),
    ("最大滑行长度", "Max sliding length"),
    ("滑行距离", "Sliding length"),
    ("滑行方案拖链长度计算", "Sliding chain length calculation"),
    ("拖链长度计算", "Cable chain length calculation"),
    ("行程长度", "Travel length"),
    ("移动端接头和支撑", "Moving-end brackets and supports"),
    ("移动端链节反装", "Flip moving-end links"),
    ("降低移动端安装高度", "Lower the moving-end height"),
    ("导向槽系统", "Guide trough system"),
    ("不带耐磨滑条的导向槽", "Guide trough without wear strip"),
    ("带耐磨滑条的导向槽", "Guide trough with wear strip"),
    ("导向槽总长度", "Total guide trough length"),
    ("导向槽总长", "Guide trough length"),
    ("耐磨滑条", "Wear-resistant sliding strip"),
    # product page labels
    ("全套固定式接头代码带扎线板", "Full set fixed bracket with tiewrap plate"),
    ("全套固定式接头代码", "Full set fixed mounting bracket code"),
    ("全套活动式接头代码", "Full set moving mounting bracket code"),
    ("内侧接头代码", "Inner mounting bracket code"),
    ("外侧接头代码", "Outer mounting bracket code"),
    ("扎线板选配", "Optional tiewrap plate"),
    ("扎线板代码", "Tiewrap plate code"),
    ("扎线板齿数", "Tiewrap plate teeth"),
    ("带扎线板", "With tiewrap plate"),
    ("预装方式", "Pre-assemble method"),
    ("固定 / 活动", "Fixed / moving"),
    ("固定式", "Locking (fixed)"),
    ("活动式", "Pivoting"),
    ("接头活动角度", "Bracket movement angle"),
    ("接头尺寸 ● 固定式 | 活动式", "Bracket size · fixed | pivoting"),
    ("接头尺寸 ● 固定式", "Bracket size · fixed"),
    ("接头尺寸 ● 活动式", "Bracket size · pivoting"),
    ("接头形式", "Bracket type"),
    ("接头类型", "Bracket type"),
    ("竖隔片数量", "No. of vertical separators"),
    ("横隔片长度", "Horizontal separator length"),
    ("横隔片数量", "No. of horizontal separators"),
    ("标准竖隔片", "Standard vertical separator"),
    ("锁紧竖隔片", "Lock vertical separator"),
    ("去应力分隔片", "Strain-relief separator"),
    ("窄脚竖隔片", "Narrow-foot vertical separator"),
    ("竖隔片", "Vertical separator"),
    ("横隔片", "Horizontal separator"),
    ("横竖隔片", "H/V separators"),
    ("内部分隔 ● 竖隔片 | 横隔片", "Inner separation · vertical | horizontal"),
    ("内部分隔 ● 竖隔片 l 横隔片", "Inner separation · vertical | horizontal"),
    ("内部分隔 ● 锁紧竖隔片", "Inner separation · lock separator"),
    ("内部分割", "Inner separation"),
    ("分隔片", "Separator"),
    ("双侧扣装", "Double-sided buckle"),
    ("单侧扣装", "Single-sided buckle"),
    ("可供选择的弯曲半径", "Available bending radius"),
    ("弯曲半径", "Bending radius"),
    ("最小弯曲半径", "Min. bending radius"),
    ("实际安装高度", "Required clearance height HF"),
    ("理论安装高度", "Theoretical installation height"),
    ("打开方式", "Opening principle"),
    ("内侧打开", "Open along inner radius"),
    ("外侧打开", "Open along outer radius"),
    ("沿内径打开", "Open along inner radius"),
    ("沿外径打开", "Open along outer radius"),
    ("内侧或外侧横杆可打开", "Crossbars openable inner or outer"),
    ("开放式拖链", "Openable cable chain"),
    ("封闭式拖链", "Enclosed cable chain"),
    ("开放式", "Openable"),
    ("封闭式", "Enclosed"),
    ("不可打开", "Non-openable"),
    ("横杆可翻转", "Reversible crossbar"),
    ("静音无尘", "Quiet and dust-free"),
    ("去应力元件", "Strain relief"),
    ("去应力", "Strain relief"),
    ("电缆夹固定", "Clamp fixing"),
    ("电缆夹", "Cable clamp"),
    ("单层电缆夹", "Single-layer clamp"),
    ("双层电缆夹", "Double-layer clamp"),
    ("三层电缆夹", "Triple-layer clamp"),
    ("扎线板 ( 外置 )", "Tiewrap plate (external)"),
    ("扎线板", "Tiewrap plate"),
    ("空位垫块", "Spacer"),
    ("外置卡扣", "External clip"),
    ("连接角铁", "Connecting angle"),
    ("安装套件", "Installation kit"),
    ("拓展件名称", "Extension part"),
    ("常用指数", "Usage index"),
    ("即将停用物料 不适用", "To be discontinued / not applicable"),
    ("即将停用物料", "To be discontinued"),
    ("不适用", "Not applicable"),
    ("图例", "Legend"),
    ("适用", "Suitable"),
    ("规格", "Series"),
    ("页码", "Page"),
    ("系列", "Series"),
    ("内高", "Inner height"),
    ("内宽", "Inner width"),
    ("外高", "Outer height"),
    ("外宽", "Outer width"),
    ("节距", "Pitch"),
    ("节数", "Links / pitch count"),
    ("链节数", "Number of links"),
    ("重量", "Weight"),
    ("型号", "Model"),
    ("产品代码", "Product code"),
    ("齿数", "Teeth number"),
    ("速度 / 加速度 FLB", "Speed / acceleration FLB"),
    ("速度 / 加速度 FLG", "Speed / acceleration FLG"),
    ("滑行速度 / 加速度", "Sliding speed / acceleration"),
    ("允许温度", "Operating temperature"),
    ("阻燃等级", "Flame-retardant rating"),
    ("拖链自摩擦系数", "Self-friction coefficient"),
    ("拖链与滑条摩擦系数", "Friction coefficient (chain & bar)"),
    ("摩擦系数", "Friction coefficient"),
    ("负载", "Load"),
    ("移动端", "Moving end"),
    ("固定端", "Fixed end"),
    ("旋转角度", "Rotation angle"),
    ("固定端角度", "Fixed-end angle"),
    ("拖链内高", "Inner height Hi"),
    ("拖链外高", "Outer height ha"),
    ("拖链内宽", "Inner width Bi"),
    ("拖链外宽", "Outer width Ba"),
    ("拖链节距", "Pitch P"),
    ("拖链长度", "Chain length LK"),
    ("拖链总重", "Total chain weight"),
    ("拖链弯曲半径", "Bending radius R"),
    ("导槽内高", "Trough inner height"),
    ("导槽外高", "Trough outer height"),
    ("导槽内宽", "Trough inner width"),
    ("导槽外宽", "Trough outer width"),
    ("导向槽内高", "Trough inner height HGi"),
    ("导向槽厚度", "Trough thickness"),
    ("滑条厚度", "Wear-strip thickness"),
    ("管线外径", "Hose / cable OD"),
    ("最大行程", "Max. travel"),
    ("最大速度", "Max. speed"),
    ("最大加速度", "Max. acceleration"),
    ("移动寿命", "Service life (cycles)"),
    ("洁净室等级", "Cleanroom class"),
    ("组件名称", "Component"),
    ("组件材质", "Material"),
    ("防滑垫片", "Anti-slip pad"),
    ("方形接头", "Square bracket"),
    ("三角形接头", "Triangular bracket"),
    ("龙骨", "Spine / support"),
    ("孔数", "Hole count"),
    ("介质", "Medium"),
    ("含量", "Ratio %"),
    ("打开方式", "Opening principle"),
    ("项目概述", "Project description"),
    ("安装类型", "Installation type"),
    ("环境数据", "Environment data"),
    ("运行参数", "Operational parameters"),
    ("空间数据", "Spatial data"),
    ("管线参数", "Cable / hose data"),
    ("其他要求", "Other requirements"),
    ("日期 | 联系方式", "Date | contact"),
    ("动态参数", "Dynamic data"),
    ("安装空间", "Installation space"),
    ("制造商 / 型号", "Maker / type"),
    ("编号", "Item no."),
    ("描述", "Description"),
    ("夹板", "Splint"),
    ("橡胶", "Rubber"),
    ("垫块", "Spacer"),
    ("工业管", "Industrial hose"),
    ("铝合金", "Aluminium alloy"),
    ("断裂伸长率 [ 干 / 湿 ]", "Elongation at break [dry / wet]"),
    ("饱和水溶液", "Saturated aqueous solution"),
    # features
    ("特点与优势", "Features & Benefits"),
    ("产品简介", "Product introduction"),
    ("产品应用要求", "Application requirements"),
    ("拖链订购示例", "Ordering example"),
    ("产品定制化服务", "Customized options"),
    ("在机床行业应用", "Machine-tool applications"),
    ("在半导体行业应用", "Semiconductor applications"),
    ("灵活小接头9可用于多种应用场合", "Compact brackets for many applications"),
    ("灵活小接头，可用于多种应用场合", "Compact brackets for many applications"),
    ("比例优化的大尺寸“提高负载能”", "Optimized large pin for higher load"),
    ("比例优化的大尺寸，提高负载能力", "Optimized large pin for higher load"),
    ("高强度限位块增加架空和负载能”", "High-strength stops increase unsupported length and load"),
    ("高强度限位块增加架空和负载能力", "High-strength stops increase unsupported length and load"),
    ("独特内部降噪结构", "Internal noise-reduction structure"),
    ("特殊小尺寸9可用于狭小空间", "Compact size for tight spaces"),
    ("优化设计的内部降噪结构", "Optimized internal noise-reduction design"),
    ("光滑的拖链内表面有效降低磨损", "Smooth inner surface reduces wear"),
    ("集成的滑行面便于长行程滑行应用", "Integrated sliding face for long travel"),
    ("卯榫结构,提高侧向承载和稳定性", "Mortise structure for lateral load and stability"),
    ("带衬套的接头防止冷裂", "Bushing brackets prevent cold cracking"),
    ("多孔位的固定式和活动式接头可以应用于多种安装场合", "Multi-hole fixed/pivoting brackets for many installations"),
    ("双重锁定的横杆,提高内部承载", "Double-lock crossbars increase inner load"),
    ("封闭式盖板,防止油污飞屑", "Enclosed lids keep out oil and chips"),
    ("可根据需求安装横竖隔片", "Optional vertical and horizontal separators"),
    ("根据需要安装横竖隔片", "Optional vertical and horizontal separators"),
    ("接头处可根据需求安装扎线板和电缆夹 ,方便固定线缆", "Optional tiewrap plates and clamps on brackets"),
    ("接头处可根据需求安装扎线板", "Optional tiewrap plates on brackets"),
    ("盖板密闭光滑,防尘防碎屑", "Sealed smooth lids, dust- and chip-proof"),
    ("四片式设计,盖板可从内外侧打开", "Four-piece design, lids open inner or outer"),
    ("两片式设计,可根据拖链宽度灵活使用", "Two-piece design, flexible to chain width"),
    ("小节距,低噪音平稳运行", "Small pitch, low-noise smooth running"),
    ("双重锁定的盖板更加稳固", "Double-lock lids for higher rigidity"),
    ("大尺寸孔销连接,强度高", "Large pin-hole connection, high strength"),
    ("可拆卸的横杆9便于拆装线缆", "Removable crossbars for easy cabling"),
    ("多重限位增加架空和负载能”", "Multiple stops increase unsupported length and load"),
    ("高强度和厚度的横杆提高内部承载能力", "Thick high-strength crossbars raise inner load"),
    ("精益镂空的侧板降低拖链自重", "Lightened side plates reduce chain weight"),
    ("精确镂空的侧板降低拖链自重", "Lightened side plates reduce chain weight"),
    ("低摩擦的滑条,确保拖链平滑运行", "Low-friction wear strips for smooth sliding"),
    ("高动态性能9适合高速高加速场合", "High dynamics for high speed and acceleration"),
    ("无孔“连接方式9零磨损9低振动", "Pin-less connection: zero wear, low vibration"),
    ("自带扎线板的接头9方便电缆的固定", "Brackets with integral tiewrap plates"),
    ("带卡槽的接头9可方便安装扎线板", "Slotted brackets for tiewrap plates"),
    ("通用型接头9可在三面安装", "Universal brackets, three-side mounting"),
    ("可翻转的封闭式盖板,防止油污飞屑", "Reversible enclosed lids keep out oil and chips"),
    ("可翻转的横杆,方便拆装线缆", "Reversible crossbars for easy cabling"),
    ("高强度双限位块增加架空和负载能力", "Dual high-strength stops raise unsupported length and load"),
    ("活塞式锁紧方式,提高稳定性和负载", "Piston lock improves stability and load"),
    ("弹性阻尼元件9极低噪音", "Elastic dampers for extra-low noise"),
    ("低噪音9小节距9运行平顺", "Low noise, small pitch, smooth running"),
    ("侧向耐磨块延长寿命", "Lateral wear pads extend service life"),
    ("简单可靠的安装套件,无需焊接", "Simple installation kit, no welding"),
    ("针对不同工况,可选用镀锌钢或者不锈钢", "Galvanized steel or stainless steel for different duties"),
    ("增加横杆 / 盖板刚性,降低宽幅重载时横杆折弯风险", "Stiffer bars/lids reduce bending on wide heavy-duty chains"),
    ("通过横杆 / 盖板拓展件,可以增加拖链的内宽", "Bar/lid extensions increase inner width"),
    ("拆装方便,可以根据需要组合不同宽度", "Easy to assemble; combine widths as needed"),
    ("可根据需求组合选取不同的宽度", "Combine different widths as required"),
    ("连接可靠,内部各腔体完全独立", "Reliable connection; chambers fully independent"),
    ("开口式底槽,无污垢积累,防腐蚀", "Open bottom profile, no dirt build-up, corrosion-resistant"),
    ("用于电缆和软管的端部固定", "For fixing cable and hose ends"),
    ("安装在接头的卡槽上或外置使用", "Mount on bracket slot or use externally"),
    ("简单高效,易于拆装,节省空间", "Simple, efficient, easy to fit, space-saving"),
    ("便于光纤或电缆的快速填装,节省装配时间和成本", "Fast fiber/cable loading, less assembly time and cost"),
    ("用于光纤或电缆的外置应用", "For external fiber or cable routing"),
    ("用于保护和夹紧电缆及气管", "Protects and clamps cables and air hoses"),
    ("标准配置:每两节拖链带 1 组卡扣", "Standard: one clip set every two links"),
    ("发货时接头如需预装配,请注明安装方式", "Specify pre-assembly of brackets when ordering"),
    ("发货时如需预装 C 型槽,请注明安装方式", "Specify C-profile pre-assembly when ordering"),
    ("发货时,拖链接头配备整套螺栓附件。", "Brackets are shipped with a full bolt kit."),
    ("可根据需求提供防静电等定制化产品", "ESD and other custom versions available"),
    ("可提供 UL94 认证 /CE 认证", "UL94 / CE certification available"),
    ("切记:拖链内部填充不可超过 65%!", "Never fill more than 65% of the inner space!"),
    ("旋转角度取决于 R", "Rotation angle depends on R"),
    ("取值区间", "Value range"),
    # recommendations
    ("推荐用于架空丶竖直悬挂或站立应用", "Recommended for unsupported, vertical hanging or standing"),
    ("推荐用于架空、  竖直悬挂或站立应用", "Recommended for unsupported, vertical hanging or standing"),
    ("推荐用于架空丶垂直悬挂或站立", "Recommended for unsupported, hanging or standing"),
    ("推荐用于竖直悬挂或站立应用", "Recommended for vertical hanging or standing"),
    ("推荐用于架空丶滑行丶竖直应用", "Recommended for unsupported, sliding or vertical use"),
    ("推荐用于架空丶竖直悬挂应用", "Recommended for unsupported or vertical hanging"),
    ("推荐用于架空丶滑行应用", "Recommended for unsupported and sliding"),
    ("推荐用于滑行应用", "Recommended for sliding"),
    ("推荐用于架空应用", "Recommended for unsupported"),
    ("推荐用竖直悬挂或站立应用", "Recommended for hanging or standing"),
    # bullets / tags
    ("● 高速度 | 快速拆装的场合", "High speed | quick assembly"),
    ("● 高速度 | 高加速度", "High speed | high acceleration"),
    ("● 轻便 | 快速拆装", "Lightweight | quick assembly"),
    ("● 长寿命 | 低噪音", "Long life | low noise"),
    ("● 长寿命 | 耐磨损", "Long life | wear-resistant"),
    ("● 密闭 | 防尘防高温碎屑", "Enclosed | dust and hot-chip protection"),
    ("● 封闭式 | 防碎屑", "Enclosed | chip protection"),
    ("● 高负载 | 长架空场合", "High load | long unsupported travel"),
    ("● 中等架空 | 中等负载", "Medium unsupported | medium load"),
    ("● 架空 | 中等负载", "Unsupported | medium load"),
    ("● 滑行 | 中等行程", "Sliding | medium travel"),
    ("● 长距型及高负载专用夹板", "Long-travel / heavy-duty clamps"),
    ("● 低磨损", "Low wear"),
    ("● 低噪音", "Low noise"),
    ("● 极低噪音", "Extra-low noise"),
    ("● 轻便", "Lightweight"),
    ("适用于高速高加速场合,可靠性佳", "Reliable for high speed and acceleration"),
    ("适用于要求高速高加速的场合", "For high-speed, high-acceleration duty"),
    ("适用于 G/GR 系列产品", "For G / GR series"),
    ("适用于 G/GR/Q40/QR40/Q52/QR52/Q62/U35", "For G/GR/Q40/QR40/Q52/QR52/Q62/U35"),
    # notes
    ("如有特殊尺寸及应用环境需求,我司可提供定制开发服务。",
     "Custom sizes and materials are available for special applications."),
    ("如需要其他尺寸的拖链,请与我们的工程师联系", "Contact our engineers for other sizes"),
    ("如需要其他尺寸的拖链,  请与我们的工程师联系", "Contact our engineers for other sizes"),
    ("★ 如需要其他尺寸的拖链,请与我们的工程师联系", "★ Contact our engineers for other sizes"),
    ("注:如有长行程应用需求,请咨询我司工程师。", "Note: consult our engineers for long-travel applications."),
    ("注: 如有长行程应用需求,请咨询我司工程师。", "Note: consult our engineers for long-travel applications."),
    ("在选型过程中有任何问题,请随时与我们联系", "Contact us anytime during selection"),
    ("可以考虑滑行设计方案,请参考长行程介绍。", "Consider a sliding design; see Long Travel."),
    ("选择一个负载更高 / 架空能力更好的拖链。", "Select a chain with higher load / unsupported capacity."),
    ("如果架空能力不足时,有以下解决方案", "If unsupported capacity is not enough:"),
    ("在架空区域增加支撑,我们推荐以下三种增加支撑的方法。", "Add supports in the unsupported area. Three options:"),
    ("1.  增加一个支撑,如图 (一),可增加 50% 的架空长度。",
     "1. Add one support (Fig. 1) to extend unsupported length by 50%."),
    ("2.  增加两个支撑,如图(二),可增加 100% 的架空长度。",
     "2. Add two supports (Fig. 2) to extend unsupported length by 100%."),
    ("3.  增加区域支撑,如图(三),最大可增加 100% 的架空长度。",
     "3. Add area supports (Fig. 3) to extend unsupported length by up to 100%."),
    ("两条对开拖链滑行:   用于有限空间或高负载", "Twin opposing sliding chains: for limited space or high load"),
    ("单条拖链滑行:", "Single sliding chain:"),
    ("以行程长度 40 米为例,按照中点安装方式计算", "Example: 40 m travel, midpoint installation"),
    ("导向槽系统是拖链滑行应用时必不可少的引导装置。",
     "A guide trough is essential for sliding applications."),
    ("针对不同的使用工况,我们可提供多种模块化导向槽组合。",
     "Modular trough combinations are available for different duties."),
    ("其中导向槽可提供不锈钢和镀锌钢两种材质。",
     "Troughs are available in stainless or galvanized steel."),
    ("滑行应用时,固定端电缆夹高度不得高于拖链外高",
     "In sliding use, fixed-end clamp height must not exceed outer height"),
    ("标注的宽度为拓展盖板,如需拓展其他宽度,详见(138)页盖板拓展部分。",
     "Marked width is a lid extension; see lid extensions on page 138."),
    ("该宽度为拓展盖板,如需拓展其他宽度,详见(138)页盖板拓展部分。",
     "This width is a lid extension; see lid extensions on page 138."),
    ("拖链固定端位于行程中点", "Fixed end at travel midpoint"),
    ("拖链固定端偏移行程中点位置", "Fixed-end offset from midpoint"),
    ("固定端偏移行程中点距离", "Midpoint offset ΔM"),
    ("架空极限位置时最小距离", "Min. distance at unsupported end position"),
    ("滑行极限位置时最小距离", "Min. distance at sliding end position"),
    ("滑行移动端反装链节数", "No. of reversed links at moving end (sliding)"),
    ("滑行时移动端安装高度", "Moving-end height in sliding use"),
    ("拖链宽度越宽,架空长度越长", "Wider chain → longer unsupported length"),
    ("拖链弯曲半径越小,架空长度越长", "Smaller radius → longer unsupported length"),
    ("架空运行姿态,对应不同的架空长度。", "Unsupported postures correspond to different lengths."),
    ("图  (一)", "Fig. 1"),
    ("图  (二)", "Fig. 2"),
    ("图  (三)", "Fig. 3"),
    ("图(二)", "Fig. 2"),
    ("图(三)", "Fig. 3"),
    ("降噪设计", "Noise-reduction design"),
    ("其它", "Others"),
    ("其它", "Other"),
    ("其它", "Others"),
    ("直线架空长度", "Straight unsupported length"),
    ("柔韧,轻薄,超长寿命", "Flexible, light, long life"),
    ("螺丝, 最大锁紧力不超过", "screws; max. tightening torque"),
    ("可定制封闭式规格", "Enclosed version available"),
    ("E 型接头:无端面安装孔", "Type E bracket: no end-face holes"),
    ("G2 型接头: 无端面安装孔", "Type G2 bracket: no end-face holes"),
    ("T1 类接头:有端面安装孔", "Type T1 bracket: with end-face holes"),
    ("黑色", "Black"),
    ("快速选型", "Quick Selection"),
    ("目录", "Contents"),
    ("术语与公式", "Terminology and Formulas"),
    ("示例", "Sample"),
    ("注意", "Attention"),
    ("内侧打开", "Inner opening"),
    ("外侧打开", "Outer opening"),
    ("产品代码 不可打开", "Product code Non-open"),
    ("可选弯曲半径", "Available Radius"),
    ("全套固定式接头", "Full set fixed mounting bracket"),
    ("全套活动式接头", "Full set moving mounting bracket"),
    ("导向槽长度", "Length of the guide trough"),
    ("节数 /m", "Numbers of Pitch/m"),
    ("节数 /m", "Numbers of Pitch/m"),
    ("架空负载", "Unsupported load"),
    ("可根据需求提供防静电产品", "ESD products can be provided as required."),
    ("可提供 UL94 / CE 认证", "UL94 certification / CE certification is available."),
    ("拖链系统", "Cable Chain System"),
    ("拖链系统", "Cable-chain System"),
]

# Full-paragraph translations (zh, en). Matched after whitespace collapse.
SENTENCES = [
    (
        "江苏威驭智能科技有限公司, 专注于运动塑料产品的研发、生产、销售和运动塑料产品定制化服务。公司总部位于上海,工厂位于常州,拥有超万平生产厂房,配备有现代化的注塑车间,高标准的模具加工车间及智能高效的装配仓库。",
        "WYW MOTION (Jiangsu) focuses on R&D, production, sales and customization of motion-plastic products. Headquartered in Shanghai with a Changzhou factory of over 10,000 m², it has a modern injection shop, high-standard mold shop and efficient assembly warehouse.",
    ),
    (
        "目前公司自主研发的 WYW 尼龙拖链、高速静音拖链、无尘拖链等产品,采用先进的加工和制造工艺, 具有高耐磨高负载, 高韧性等特点, 可满足多种应用场景的要求, 广泛应用于机床、激光、汽车、医疗、港口、半导体、新能源、自动化等行业。",
        "WYW nylon, high-speed quiet and cleanroom cable chains are developed in-house with advanced processing. They offer high wear resistance, load capacity and toughness for machine tools, laser, automotive, medical, ports, semiconductor, new energy and automation.",
    ),
    (
        "我司各系列产品都通过了严格的粉尘、噪音、耐疲劳等测试,并有防火、阻燃、防静电、防腐蚀、无尘等权威机构认证证书。",
        "All series have passed strict dust, noise and fatigue tests, with fire, flame-retardant, ESD, corrosion and cleanroom certifications from accredited bodies.",
    ),
    (
        "得益于本土化的生产优势,我们可以保证快速的交付周期 (1-3 天 )。另我司有便捷的选型软件和 3D模型库,并配备专业的工程师团队,7x24 小时为您提供选型沟通和技术咨询。",
        "Localized production enables 1–3 day delivery. Selection software, a 3D library and a 24/7 engineering team support product choice and technical advice.",
    ),
    (
        "WYW MOTION (Jiangsu) focus on research and development, driving our production, sales and customized services of injection mold plastic products,with a factory spanning over 12,000 square meters in Changzhou. This facility is equipped with a modern injection molding workshop, a high-quality mold pro",
        "江苏威驭智能科技专注注塑运动塑料的研发、生产、销售与定制，常州工厂超 12,000 平方米，配备现代化注塑车间与高标准模具加工能力。",
    ),
    (
        "We have independently developed innovative products, including WYW nylon cable chains and dust- free cable chains, utilizing advanced processing and manufacturing techniques. These products excel in wear resistance, load-bearing capacity and durability, catering to various application scenarios and",
        "我们自主研发 WYW 尼龙拖链与无尘拖链，采用先进加工工艺，耐磨、承重与耐久性出色，可覆盖多种应用场景。",
    ),
    (
        "All our products series have undergone rigorous tests for dust, noise, and fatigue resistance, and have received certifications from authoritative institutions for fire resistance, ATEX/ESD compliance, and corrosion resistance.",
        "各系列产品均通过粉尘、噪音与疲劳测试，并获得防火、ATEX/ESD 及耐腐蚀等权威认证。",
    ),
    (
        "Benefit by our localized production capabilities, we guarantee a swift delivery period of 1-3 days. Futhermore, we provide convenient selection software and a 3D model library, supported by a team of professional engineers available 24/7 to oﬀer product selection advice and technical consultations.",
        "依托本土化生产，交期 1–3 天。并提供选型软件、3D 模型库及 7×24 小时工程师选型与技术咨询。",
    ),
    (
        "WYW's vision is to become a world-class expert in injection mold plastic products, dedicated to delivering superior products and services to our customers.",
        "威驭愿景：成为世界级运动塑料专家，为客户提供更优产品与服务。",
    ),
    (
        "架空定义: 拖链在运行过程中,拖链的上部未接触下部。",
        "Unsupported: the upper run does not touch the lower run during motion.",
    ),
    (
        "架空长度: 移动端到拖链弯曲半径圆弧末端的距离。",
        "Unsupported length: distance from the moving end to the end of the radius arc.",
    ),
    (
        "架空应用是拖链最常见的应用,架空长度取决于拖链的类型以及内部的负载情况。一般情况下10m 以内的行程都可以用架空来实现。",
        "Unsupported travel is the most common layout. Length depends on chain type and fill weight. Travels within about 10 m can usually be unsupported.",
    ),
    (
        "WYW 拖链合理的结构设计决定了其高负载的特性,适用于高速高加速长行程架空的场合,并可延长拖链使用寿命。",
        "WYW structural design gives high load capacity for high-speed, high-acceleration unsupported travel and longer service life.",
    ),
    (
        "当设计行程超过拖链架空负载范围时,采用滑行方案可实现长距离的移动供电,行程最长可达几百米,因此滑行方案目前是广泛应用于汽车,港口等行业的安全便捷的供电方式。",
        "When travel exceeds unsupported capacity, a sliding solution can power travels of hundreds of metres — widely used in automotive and port applications.",
    ),
    (
        "拖链的上段以下段为支撑,上段一部分拖链在下段拖链上滑行,另一部分在同高的耐磨滑条上滑行,为防止侧向偏移,必须使用导向槽系统。",
        "The upper run rides on the lower run and on wear strips of the same height. A guide trough is required to prevent lateral offset.",
    ),
    (
        "WYW 拖链从结构设计到原材料选择都非常适用于长行程的滑行应用,其中 U 系列和 G 系列产品具有高耐磨、低噪音、良好的直线度等特点,可大大延长拖链使用寿命。",
        "From structure to materials, WYW chains suit long sliding duty. U and G series offer high wear resistance, low noise and straightness for longer life.",
    ),
    (
        "在选型设计时,我们推荐将拖链固定端安装在行程中点,此时所需拖链、电缆及软管长度最短,成本最低。",
        "Place the fixed end at travel midpoint to use the shortest chain, cables and hoses at the lowest cost.",
    ),
    (
        "站立应用是指拖链在竖直方向上运行,弯曲半径段向上拱起。",
        "Standing: the chain runs vertically with the radius arching upward.",
    ),
    (
        "悬挂应用是指拖链在竖直方向上运行,弯曲半径段向下拱起。",
        "Hanging: the chain runs vertically with the radius arching downward.",
    ),
    (
        "侧倒应用是指拖链侧倒安装,沿着水平方向做直线往复运动。",
        "Side-mounted straight: the chain is laid on its side and travels horizontally.",
    ),
    (
        "旋转应用是指拖链侧倒安装,沿着水平方向做旋转往复运动。",
        "Rotary: the chain is side-mounted and travels along a circular path.",
    ),
    (
        "在桁架机械手、机床、激光等行业,竖直站立是常见的拖链安装方式。在此工况下,由于拖链需要承担自重及线缆的重量,有侧向倾倒的风险,因此一般行程较短。",
        "Standing is common on gantries, machine tools and lasers. The chain carries its own weight and the cables, so travel is usually short to avoid tipping.",
    ),
    (
        "在工程机械、机器人、桁架机械手、物流仓储等行业,竖直悬挂是常见的拖链安装方式。在此工况下,由于拖链无需承担内部线缆的重量,因此行程可达到数百米。",
        "Hanging is common on construction machinery, robots, gantries and logistics. The chain does not carry inner cable weight, so travel can reach hundreds of metres.",
    ),
    (
        "在机器人、机床、激光等行业,由于设备的安装空间受限制,侧倒应用是常见的安装方式。",
        "Side-mounted layouts are common on robots, machine tools and lasers when space is limited.",
    ),
    (
        "在机器人、工程机械、军工航天等行业,由于设备的安装空间和运行方式等原因,旋转应用是常见的安装方式。",
        "Rotary layouts are common on robots, construction machinery and aerospace equipment.",
    ),
    (
        "拖链内部的电缆和介质管必须尽量均匀分布,相互分隔, 保证在运行过程中管线周围留有一定的间隙,可以自由移动,以免引起管线的B绕、磨损和相互挤压,影响拖链和管线的使用寿命,因此管线的排布和内腔分隔就尤为重要。",
        "Cables and hoses must be evenly spaced and separated so they can move freely, avoiding twist, wear and crushing that shorten chain and cable life.",
    ),
    (
        "原则   不同材质的管线需使用分隔片分隔。",
        "Rule: separate different materials with separators.",
    ),
    (
        "圆电缆 空间允许的情况,尽量使用竖隔片隔开。",
        "Round cables: use vertical separators wherever space allows.",
    ),
    (
        "扁电缆 多条扁电缆并排布置时需使用竖隔片分隔开来,叠放时需使用横隔片分隔。",
        "Flat cables: separate side-by-side with vertical separators, stacked with horizontal separators.",
    ),
    (
        "气管   一般的气管排布可参考圆电缆,对于橡胶气管,建议增加间隙,避免粘结。",
        "Air hoses: follow round-cable rules; increase clearance for rubber hoses to avoid sticking.",
    ),
    (
        "液压管 使用液压管时,需注意加压时的管套的膨胀现象,拖链中必须保留足够的间隙。",
        "Hydraulic hoses: allow extra clearance for expansion under pressure.",
    ),
    (
        "如果满足上述规则,则相邻的电缆及介质管,则不需要使用分隔片。",
        "If the rules above are met, adjacent cables/hoses may not need separators.",
    ),
    (
        "如果满足上述规则,则相邻的电缆及介质管,则必须需要使用竖隔片或者横隔片降低内高。",
        "If required by the rules above, use vertical or horizontal separators to reduce inner height.",
    ),
    (
        "水平安装 _ 需要确保电缆和软管的重量沿宽度方向对称均匀分布,否则,拖链的一侧会磨损加重, 进而缩短拖链的使用寿命。因此排布时,尽量把重的管线放在两侧。",
        "Horizontal install: distribute weight symmetrically across the width; place heavier lines toward both sides to avoid uneven wear.",
    ),
    (
        "侧倒安装 _ 设计时需要确保内部管线的重量从上往下由轻到重分布,避免拖链倾倒的风险。",
        "Side-mounted: stack weight light-to-heavy from top to bottom to prevent tipping.",
    ),
    (
        "拖链的弯曲半径取决于设计使用的电缆或者介质管的最大横向尺寸和最大硬度,应不小于内部管线所允许的最小弯曲半径。在拖链运行过程中,内部线缆应处于自然状态的曲张,并有足够的自由空间,避免在弯曲半径处受到张力而加剧磨损。",
        "Choose a radius no smaller than the cables/hoses allow. Inner lines must flex freely without tension in the bend, or wear will increase.",
    ),
    (
        "长行程应用中,方案设计和拖链选型对后期拖链的运行状态和使用寿命影响巨大,因此我们建议在长行程的设计时请咨询我司设计工程师, 我们将免费提供设计方案、图纸型号、管线排布、安装指导等相关咨询服务。",
        "Long-travel layout and selection strongly affect life. Consult our engineers — design, drawings, cable layout and installation advice are free.",
    ),
    (
        "在拖链滑行应用时,除了降低安装高度,还需要移动端拖链反装几节,如右图所示,以降低拖链应力集中,避免拖链拱起现象。",
        "For sliding duty, besides lowering the moving end, reverse several moving-end links as shown to reduce strain and prevent arching.",
    ),
    (
        "在滑行应用中,我们推荐用活动式接头作为标准配置,活动式接头可以减轻拖链两端链节的承载,避免应力集中。",
        "For sliding, use pivoting brackets as standard to unload the end links and avoid stress concentration.",
    ),
    (
        "拖链在滑行应用中,如移动端高度较高,拖链悬空段太长,拖链退回时会造成负载过大以致于有折断的风险。",
        "If the moving end is too high in sliding use, the hanging section overloads on return and may break.",
    ),
    (
        "接头 一 我们推荐使用固定式接头作为竖直站立的标准配置, 可以一定程度上避免拖链在运行过程中的摆动。",
        "Brackets: use locking brackets as standard for standing to reduce swinging.",
    ),
    (
        "接头 一 我们推荐使用固定式接头作为侧倒应用的标准配置,可以一定程度上避免拖链在运行过程中的摆动。",
        "Brackets: use locking brackets as standard for side-mounted travel to reduce swinging.",
    ),
    (
        "接头 一 我们推荐使用固定式接头作为竖直应用悬挂的标准配置, 可以减小拖链在运行过程中的摆动。",
        "Brackets: use locking brackets as standard for hanging to reduce swinging.",
    ),
    (
        "接头 一 我们推荐使用活动式接头作为旋转应用的标准配置,活动式式接头可以更贴合运行的轨道。",
        "Brackets: use pivoting brackets as standard for rotary travel to follow the path.",
    ),
    (
        "横向挡板 一 当拖链有横向加速度时,为防止拖链摆动的风险,我们建议安装横向支撑挡板。",
        "Side guides: fit lateral supports when there is lateral acceleration, to stop swinging.",
    ),
    (
        "横向挡板 一 当拖链有横向加速度时,为防止倾倒的风险,我们建议安装横向支撑挡板。",
        "Side guides: fit lateral supports when there is lateral acceleration, to prevent tipping.",
    ),
    (
        "电缆夹 一 当拖链竖直悬挂安装时,为防止额外的拉力作用在内部管线上,我们建议在接头处安装电缆夹等去应力原件,以防止在长行程悬挂时有管线磨损和内芯断裂的风险。",
        "Clamps: on hanging travel, fit strain relief at the brackets so inner cables are not pulled, worn or broken.",
    ),
    (
        "底部支撑 一 对于低负载或者短行程的侧倒安装时,拖链可以悬空使用,当需要增大行程且拖链内部负载较高时,需要增加底部支撑,如左图所示。另外在实际应用中:",
        "Bottom support: short/light side-mounted chains may hang free; longer or heavier duty needs a bottom support as shown.",
    ),
    (
        "管线排布 一 当拖链侧倒安装时, 内部管线因为自身重力的因素,会对底部的线缆造成挤压,导致电缆磨损,因此我们建议使用竖隔片,并且管线排布也要遵循上轻下重的规律,具体请参考拖链布线介绍。",
        "Layout: in side-mounted use, gravity crushes lower cables — use vertical separators and stack light-to-heavy. See cable-layout pages.",
    ),
    (
        "管线排布 一 当拖链侧倒旋转安装时, 同样由于内部管线因为自身重力的因素,会对底部的线缆造成挤压,导致电缆磨损,因此我们建议使用竖隔片,并且管线排布也要遵循上轻下重的规律,具体请参考拖链布线介绍。",
        "Layout: in rotary side-mounted use, gravity crushes lower cables — use vertical separators and stack light-to-heavy.",
    ),
    (
        "长度及弯曲半径计算 一 拖链在旋转运动时, 可以沿外轨道或者内轨道进行回转,具体设计计算请咨询我们的工程师。",
        "Length and radius: rotary chains may run on the outer or inner track. Ask our engineers for calculation.",
    ),
    (
        "预应力 一 为防止拖链侧向拱起,我们推荐使用WYW 拖链无预应力版本的拖链,如遇其他设计问题,请咨询我们的工程师。",
        "Camber: to prevent side bowing, we recommend the non-camber version. Contact us for other design issues.",
    ),
    (
        "圆电缆: 外径的 10%",
        "Round cable: 10% of OD",
    ),
    (
        "扁电缆: 宽度和厚度各 10%",
        "Flat cable: 10% of width and thickness",
    ),
    (
        "气管:  外径的 5_10%",
        "Air hose: 5–10% of OD",
    ),
    (
        "介质管: 外径的 15_20%",
        "Media hose: 15–20% of OD",
    ),
    (
        "液压管: 外径的 20%",
        "Hydraulic hose: 20% of OD",
    ),
    (
        "公司地址:江苏省常州市天宁区武青北路6号听松大厦306室",
        "Office: Room 306, Tingsong Building, No. 6 Wuqing North Road, Tianning, Changzhou, Jiangsu",
    ),
    (
        "工厂地址:江苏省常州市武进区洛阳镇谈家头创胜路7号",
        "Factory: No. 7 Chuangsheng Road, Tanjiatou, Luoyang Town, Wujin, Changzhou, Jiangsu",
    ),
    (
        "电话:0519-86682122",
        "Tel: 0519-86682122",
    ),
    (
        "邮箱: info@wywmotion.com",
        "Email: info@wywmotion.com",
    ),
    (
        "网址: www.wywmotion.com",
        "Website: www.wywmotion.com",
    ),
]
